#!/bin/bash
# Created by: Seb Blair
# Date Created: 23/11/2020
# Version 1.1


NTHCORE=$(lscpu|awk 'NR==3 {print $2}')
echo "                   CORE 0    CORE 1    CORE 2    CORE 3" # column headings 19 4 4 4  white spaces 

for i in /sys/devices/system/cpu/cpu0/cpufreq/{cpuinfo,scaling}_*; do #iterate over the all cput frequencies 
  PNAME=$(basename $i)

  [[ "$PNAME" == *available* ]] || [[ "$PNAME" == *transition* ]] || \
  [[ "$PNAME" == *driver* ]]    || [[ "$PNAME" == *setspeed* ]] && continue

  echo "$PNAME: "

  for (( j = 0; j < ${NTHCORE}; j++ ));do
    KPARAM=$(echo $i | sed "s/cpu0/cpu$j/") # replace cpu0 with cpuj for  /sys/devices/system/cpu/cpuj/cpufreq...
    sudo cat $KPARAM
  done

done | paste - - - - - | column -t
