#!/bin/bash
# Created by: Seb Blair
# Date Created: 23/11/2020
# Version: 1.0

USAGE(){
         echo -e  $1
         echo -e "\nUsage: [-v version]"
}


VERSION="Version: 1.0"
AUTHOR="Author: Seb Blair"
RELEASED="Release Date: 2020-11-23"


GOVDIR="/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"

AVAILGOVS=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)

while [[ 1 ]]; do
	echo "Please select from the following governors:"
	echo  "${AVAILGOVS}"

	read GOV
	# use grep to match input with sub string of AVAILGOVS
	if grep -q "$GOV" <<< "${AVAILGOVS}"; then
		break
	fi
done

echo -n "Changing the scaling_governor for CPU 0 1 2 3 to "

echo "${GOV}" | sudo tee ${GOVDIR}
echo "Success your new Scaling Governor is ${GOV}"
